package packVista;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import packControlador.GestorBuscaminas;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

public class IU_MostrarDatosNivel extends JFrame {
    private JPanel rootPanel;
    private JButton volverConfButton;
    private JTextField textFieldlevel;
    private JTextField textFieldFilas;
    private JTextField textFieldColumnas;
    private JTextField textFieldtiempo;
    private JPanel infoNivelPanel;
    private JPanel buttonpanel;
    private JPanel infoPanel;
    private JLabel lblnivel;
    private JLabel lblfilas;
    private JLabel lblcolumnas;
    private JLabel lbltiempo;
    private JTextField textFieldMinas;

    public IU_MostrarDatosNivel(int pLevel) throws SQLException {
        setTitle("Mostrar Datos Nivel");
        setResizable(false);
        setContentPane(rootPanel);

        añadirDatos(pLevel);

        volverConfButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                back();
            }
        });
    }

    private void añadirDatos(int nivel) {
        textFieldlevel.setEditable(false);
        textFieldlevel.setText("Nivel " + nivel);
        int filas = GestorBuscaminas.getMiGB().obtenerfilasnivel(nivel);
        textFieldFilas.setText("" + filas);
        Integer columnas = GestorBuscaminas.getMiGB().obtenercolumnasnivel(nivel);
        textFieldColumnas.setText("" + columnas);
        textFieldMinas.setText("" + nivel * columnas);
    }

    private void back() {
        dispose();
        IU_Consultarinfojuego juego = null;
        try {
            juego = new IU_Consultarinfojuego();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        juego.setPreferredSize(new Dimension(570, 320));
        juego.pack();
        juego.setLocationRelativeTo(null);
        juego.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.setBackground(new Color(-9999251));
        rootPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Datos del Nivel Seleccionado", TitledBorder.LEFT, TitledBorder.BELOW_TOP, this.$$$getFont$$$("Microsoft JhengHei", Font.BOLD, 14, rootPanel.getFont()), new Color(-590081)));
        infoNivelPanel = new JPanel();
        infoNivelPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        infoNivelPanel.setBackground(new Color(-590081));
        rootPanel.add(infoNivelPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        infoPanel = new JPanel();
        infoPanel.setLayout(new GridLayoutManager(6, 4, new Insets(0, 0, 0, 0), -1, -1));
        infoPanel.setBackground(new Color(-590081));
        infoNivelPanel.add(infoPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        lblnivel = new JLabel();
        Font lblnivelFont = this.$$$getFont$$$("Microsoft JhengHei", -1, 14, lblnivel.getFont());
        if (lblnivelFont != null) lblnivel.setFont(lblnivelFont);
        lblnivel.setText("  Nivel Seleccionado");
        infoPanel.add(lblnivel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblfilas = new JLabel();
        Font lblfilasFont = this.$$$getFont$$$("Microsoft JhengHei", -1, 14, lblfilas.getFont());
        if (lblfilasFont != null) lblfilas.setFont(lblfilasFont);
        lblfilas.setText("Número de Filas");
        infoPanel.add(lblfilas, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblcolumnas = new JLabel();
        Font lblcolumnasFont = this.$$$getFont$$$("Microsoft JhengHei", -1, 14, lblcolumnas.getFont());
        if (lblcolumnasFont != null) lblcolumnas.setFont(lblcolumnasFont);
        lblcolumnas.setText("Número de Columnas");
        infoPanel.add(lblcolumnas, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lbltiempo = new JLabel();
        Font lbltiempoFont = this.$$$getFont$$$("Microsoft JhengHei", -1, 14, lbltiempo.getFont());
        if (lbltiempoFont != null) lbltiempo.setFont(lbltiempoFont);
        lbltiempo.setText("Tiempo límite (en seg)");
        infoPanel.add(lbltiempo, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldlevel = new JTextField();
        textFieldlevel.setBackground(new Color(-590081));
        textFieldlevel.setEditable(false);
        textFieldlevel.setEnabled(true);
        Font textFieldlevelFont = this.$$$getFont$$$("Microsoft JhengHei", Font.BOLD, 14, textFieldlevel.getFont());
        if (textFieldlevelFont != null) textFieldlevel.setFont(textFieldlevelFont);
        textFieldlevel.setHorizontalAlignment(0);
        infoPanel.add(textFieldlevel, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        textFieldFilas = new JTextField();
        textFieldFilas.setBackground(new Color(-590081));
        textFieldFilas.setEditable(false);
        Font textFieldFilasFont = this.$$$getFont$$$("Microsoft JhengHei", Font.BOLD, 14, textFieldFilas.getFont());
        if (textFieldFilasFont != null) textFieldFilas.setFont(textFieldFilasFont);
        textFieldFilas.setHorizontalAlignment(0);
        infoPanel.add(textFieldFilas, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        textFieldColumnas = new JTextField();
        textFieldColumnas.setBackground(new Color(-590081));
        textFieldColumnas.setEditable(false);
        Font textFieldColumnasFont = this.$$$getFont$$$("Microsoft JhengHei", Font.BOLD, 14, textFieldColumnas.getFont());
        if (textFieldColumnasFont != null) textFieldColumnas.setFont(textFieldColumnasFont);
        textFieldColumnas.setHorizontalAlignment(0);
        infoPanel.add(textFieldColumnas, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        textFieldtiempo = new JTextField();
        textFieldtiempo.setBackground(new Color(-590081));
        textFieldtiempo.setEditable(false);
        Font textFieldtiempoFont = this.$$$getFont$$$("Microsoft JhengHei", Font.BOLD, 14, textFieldtiempo.getFont());
        if (textFieldtiempoFont != null) textFieldtiempo.setFont(textFieldtiempoFont);
        textFieldtiempo.setHorizontalAlignment(0);
        textFieldtiempo.setText("No disponible");
        infoPanel.add(textFieldtiempo, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-590081));
        label1.setForeground(new Color(-590081));
        label1.setText(".");
        infoPanel.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setForeground(new Color(-590081));
        label2.setText(".");
        infoPanel.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setForeground(new Color(-590081));
        label3.setText(".");
        infoPanel.add(label3, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$("Microsoft JhengHei", -1, 14, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setText("Número de Minas");
        infoPanel.add(label4, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldMinas = new JTextField();
        textFieldMinas.setBackground(new Color(-590081));
        textFieldMinas.setEditable(false);
        Font textFieldMinasFont = this.$$$getFont$$$("Microsoft JhengHei", Font.BOLD, 14, textFieldMinas.getFont());
        if (textFieldMinasFont != null) textFieldMinas.setFont(textFieldMinasFont);
        textFieldMinas.setForeground(new Color(-12828863));
        textFieldMinas.setHorizontalAlignment(0);
        infoPanel.add(textFieldMinas, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        buttonpanel = new JPanel();
        buttonpanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        buttonpanel.setBackground(new Color(-590081));
        infoNivelPanel.add(buttonpanel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        volverConfButton = new JButton();
        volverConfButton.setBackground(new Color(-590081));
        Font volverConfButtonFont = this.$$$getFont$$$("Microsoft JhengHei", Font.BOLD, 14, volverConfButton.getFont());
        if (volverConfButtonFont != null) volverConfButton.setFont(volverConfButtonFont);
        volverConfButton.setForeground(new Color(-12828863));
        volverConfButton.setText("Volver a la configuración");
        buttonpanel.add(volverConfButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setForeground(new Color(-590081));
        label5.setText(".");
        buttonpanel.add(label5, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setForeground(new Color(-590081));
        label6.setText(".");
        infoNivelPanel.add(label6, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}